export {default as Header} from "./Header/Header"
export {default as Footer} from "./Footer/Footer"
export {default as Container} from "./Container/Contain"
export {default as Hero} from "./Hero/Hero"
export {default as Hero1} from "./Hero/Hero.jsx"